FROM node:20-alpine AS builder

WORKDIR /usr/app

COPY package*.json ./

RUN npm ci || npm install

COPY . .

RUN npm run build

FROM node:20-alpine

WORKDIR /usr/app

ENV NODE_ENV=production

RUN npm install -g serve

COPY --from=builder /usr/app/dist ./dist

CMD ["serve", "-s", "dist", "-l", "3000"]
