FROM node:20-slim

WORKDIR /usr/app

# Установка OpenSSL для Prisma
RUN apt-get update && \
    apt-get install -y openssl && \
    rm -rf /var/lib/apt/lists/*

COPY package.json yarn.lock ./

# Копируем prisma схему
COPY prisma ./prisma

# Устанавливаем все зависимости (включая dev для prisma CLI)
RUN yarn install

# Генерируем Prisma Client
RUN yarn prisma:generate

CMD ["npx", "prisma", "studio", "--hostname", "0.0.0.0", "--port", "5555", "--browser", "none"]

