FROM node:18.17.0 AS builder

WORKDIR /usr/app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

FROM node:18.17.0

WORKDIR /usr/app

ENV NODE_ENV=production

COPY package.json yarn.lock ./

RUN yarn install --production=true

COPY --from=builder /usr/app/dist ./dist

CMD ["yarn", "start:prod"]
