FROM node:18.17.0 AS builder

WORKDIR /usr/app

COPY package*.json ./

RUN npm ci || npm install

COPY . .

RUN npm run build

FROM node:18.17.0

WORKDIR /usr/app

ENV NODE_ENV=production

COPY --from=builder /usr/app/package*.json ./

RUN npm ci --omit=dev || npm install --omit=dev

COPY --from=builder /usr/app/.next ./.next
COPY --from=builder /usr/app/public ./public

CMD ["npm", "run", "start"]
