FROM node:20-alpine AS builder

WORKDIR /usr/app

COPY package*.json ./

RUN npm ci || npm install

COPY . .

RUN npm run build

FROM node:20-alpine

WORKDIR /usr/app

ENV NODE_ENV=production

COPY --from=builder /usr/app/package*.json ./

RUN npm ci --omit=dev || npm install --omit=dev

COPY --from=builder /usr/app/.next ./.next
RUN mkdir -p ./public
COPY --from=builder /usr/app/public ./public

CMD ["npm", "run", "start"]
